# To set the allowed Profile amount per group, add the permission:
# itemfilter.profiles.max.x (x being numeric amount)
# The following permission applies by default:
# itemfilter.profiles.max.9
# Effectively allowing any user to create a max of 9 profiles
# The maximum supported profile amount is 9 and minimum 1.

# Add or remove 'itemfilter' to allow the use of the item filter.
# Add or remove 'itemfilter.gui' to allow the use of the GUI.

itemfilter:
  items:
    cat1name:       'Armor and Weapons'
    cat1icon:       'DIAMOND_HELMET'
    cat1items:      [STONE, GRASS]
    cat2name:       'Tools'
    cat2icon:       'DIAMOND_PICKAXE'
    cat2items:      [STONE, GRASS]
    cat3name:       'Valuables'
    cat3icon:       'GOLD_BLOCK'
    cat3items:      [STONE, GRASS]
    cat4name:       'Potion Supplies'
    cat4icon:       'GLASS_BOTTLE'
    cat4items:      [STONE, GRASS]
    cat5name:       'Blocks'
    cat5icon:       'GRASS'
    cat5items:      [STONE, GRASS]
    cat6name:       'Farming'
    cat6icon:       'SEEDS'
    cat6items:      [STONE, GRASS]
    cat7name:       'Raiding Supplies'
    cat7icon:       'TNT'
    cat7items:      [STONE, GRASS]

  chat:
    error:          '&cYou are not allowed to use this command!'
    status:
      enabled:      '&6&lITEM FILTER &r&7Has been &aenabled&b.'
      disabled:     '&6&lITEM FILTER &r&7Has been &cdisabled&b.'
    profileset:     '&6&lITEM FILTER &r&7Profile set to: &6%NAME%.'

    profile:
      error:        '&cProfile name can not be longer than 12 or shorter than 3. Please try another.'
      invalid:      '&cProfile name contains invalid characters. Please try another.'
      exists:       '&cA profile with that name already exists. Please try another.'
      success:      '&aProfile name has been set to &b%NAME%&a.'

    menu:
      profiles:
        title:      '&9Item Pickup Filter'
        enable:     '&a&lEnable Item Filter'
        disable:    '&c&lDisable Item Filter'
        current:    '&aCurrently active profile'
        activate:   '&7Activate Profile'
        left:       '&aLeft click &7to edit'
        right:      '&aRight click &7to change name'
        chatmsg:    '&6&lITEM FILTER &r&7&lType in the new name of your profile.'
        enablmsg:   '&a&lEnabled'
        disablmsg:  '&c&lDisabled'

        msglore1:   '&7Show messages when profiles'
        msglore2:   '&7switch automatically.'

      item:
        title:      '&7Select Items'
        update:     '&6&lITEM FILTER &r&7Profile icon updated.'

      edit:
        title:      '&9Edit Profile: &b%NAME%' #Max characters: 24 INCL. color codes
        error:      '&cA different profile already has this flag. &l(%NAME%)'

        err_lore1:  '&c&lError! &r&7A different profile'
        err_lore2:  '&7already has this flag.'
        err_lore3:  '&7(%NAME%)'

        wild_name:  '&2&lWilderness'
        all_name:   '&5&lAlly'
        enem_name:  '&4&lEnemy'
        truc_name:  '&d&lTruce'
        peac_name:  '&d&lPeaceful'
        own_name:   '&a&lOwn land'
        neut_name:  '&e&lNeutral land'

        lore1: '&7Enabling will automatically activate'
        lore2: '&7the profile when you enter'
        lore3: '&7this land.'